file:
    image-path: /recipel/img
logging:
    config: classpath:logback-spring.xml
mqtt:
    clientid: mqttjs_e8022a4d0b
    host: tcp://mysql.open108.com:433
    keepalive: 2000
    password: admin
    timeout: 1000
    topic: topic1
    username: admin
mtqq:
    HOST: tcp://mysql.open108.com:433
pagehelper:
    helperDialect: mysql
    params: count=countSql
    reasonable: true
    supportMethodsArguments: true
server:
    port: 7001
spring:
    aop:
        auto: true
        proxy-target-class: true
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        initial-size: 10
        log-abandoned: true
        max-active: 500
        max-idle: 20
        max-wait: 1000
        min-evictable-idle-time-millis: 600000
        min-idle: 5
        password: cdutcm@123
        remove-abandoned: true
        remove-abandoned-timeout: 180
        test-on-borrow: true
        test-while-idle: true
        time-between-eviction-runs-millis: 300000
        url: jdbc:mysql://127.0.0.1:3307/chd6?characterEncoding=utf8&useSSL=false&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true
        username: sgkj
        validation-query: select 1 from dual
    datasourceHis:
        driver-class-name: oracle.jdbc.driver.OracleDriver
        password: 123
        url: jdbc:oracle:thin:@210.41.215.22:1521:orcl
        username: sgkj
    freemarker:
        request-context-attribute: request
    http:
        multipart:
            maxFileSize: -1
            maxRequestSize: -1
    mqtt:
        clientid: mqttId
        keepalive: 20
        password: password
        timeout: 10
        topic: topic
        url: tcp://10.126.6.46:1883
        username: admin
    mvc:
        static-path-pattern: /**
    redis:
        host: 127.0.0.1
        password: cdutcm@123
        port: 6379
    resources:
        static-locations: classpath:/file/,classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,
    jackson:
      default-property-inclusion: non_null
url:
    serverName: ks.mamios.com
    serverPort: 5000
web:
    upload-path: D:/temp/study13/
webimg:
    src: /opt/cdutcm/jenkins/ybm/data
wsUrl: '"ws://210.41.215.69:4480"'
