package com.cdutcm.tcms.biz.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.cdutcm.tcms.biz.model.Material;
import com.cdutcm.tcms.biz.model.RecipelItem;
import org.springframework.stereotype.Repository;

@Repository
public interface MaterialMapper {
	
	//查出所有药品
	List<Material> selectAll();
	//修改拼音
	int updatePinyin(List<Material> ma1);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material
     *
     * @mbggenerated Wed May 09 16:40:58 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material
     *
     * @mbggenerated Wed May 09 16:40:58 CST 2018
     */
    int insert(Material record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material
     *
     * @mbggenerated Wed May 09 16:40:58 CST 2018
     */
    int insertSelective(Material record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material
     *
     * @mbggenerated Wed May 09 16:40:58 CST 2018
     */
    Material selectByPrimaryKey(Long id);
    /*根据名字查询*/
    Material selectByName(String  name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material
     *
     * @mbggenerated Wed May 09 16:40:58 CST 2018
     */
    int updateByPrimaryKeySelective(Material record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material
     *
     * @mbggenerated Wed May 09 16:40:58 CST 2018
     */
    int updateByPrimaryKey(Material record);
    
    List<Material> findByDurgList(List<RecipelItem> recipelItem);
    
    List<Material> findbynameorpinyin(@Param("material")String material);
    
    List<Material> listPagefindmaterial(Material material);
}