package com.cdutcm.tcms.biz.model;

import com.cdutcm.core.page.Page;

public class Material {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.id
     *
     * @mbggenerated Wed May 09 16:40:58 CST 2018
     */
    private Long id;
    
    private Page page;

    private String fscode;

    public Page getPage() {
		return page;
	}

	public void setPage(Page page) {
		this.page = page;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.name
     *
     * @mbggenerated Wed May 09 16:40:58 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.pinyin
     *
     * @mbggenerated Wed May 09 16:40:58 CST 2018
     */
    private String pinyin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.max_dosage
     *
     * @mbggenerated Wed May 09 16:40:58 CST 2018
     */
    private Double maxDosage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.min_dosage
     *
     * @mbggenerated Wed May 09 16:40:58 CST 2018
     */
    private Double minDosage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.unit
     *
     * @mbggenerated Wed May 09 16:40:58 CST 2018
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.xw
     *
     * @mbggenerated Wed May 09 16:40:58 CST 2018
     */
    private String xw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.gj
     *
     * @mbggenerated Wed May 09 16:40:58 CST 2018
     */
    private String gj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.gx
     *
     * @mbggenerated Wed May 09 16:40:58 CST 2018
     */
    private String gx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.zz
     *
     * @mbggenerated Wed May 09 16:40:58 CST 2018
     */
    private String zz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.yf
     *
     * @mbggenerated Wed May 09 16:40:58 CST 2018
     */
    private String yf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.forbidden
     *
     * @mbggenerated Wed May 09 16:40:58 CST 2018
     */
    private String forbidden;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.id
     *
     * @return the value of material.id
     *
     * @mbggenerated Wed May 09 16:40:58 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.id
     *
     * @param id the value for material.id
     *
     * @mbggenerated Wed May 09 16:40:58 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.name
     *
     * @return the value of material.name
     *
     * @mbggenerated Wed May 09 16:40:58 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.name
     *
     * @param name the value for material.name
     *
     * @mbggenerated Wed May 09 16:40:58 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.pinyin
     *
     * @return the value of material.pinyin
     *
     * @mbggenerated Wed May 09 16:40:58 CST 2018
     */
    public String getPinyin() {
        return pinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.pinyin
     *
     * @param pinyin the value for material.pinyin
     *
     * @mbggenerated Wed May 09 16:40:58 CST 2018
     */
    public void setPinyin(String pinyin) {
        this.pinyin = pinyin == null ? null : pinyin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.max_dosage
     *
     * @return the value of material.max_dosage
     *
     * @mbggenerated Wed May 09 16:40:58 CST 2018
     */
    public Double getMaxDosage() {
        return maxDosage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.max_dosage
     *
     * @param maxDosage the value for material.max_dosage
     *
     * @mbggenerated Wed May 09 16:40:58 CST 2018
     */
    public void setMaxDosage(Double maxDosage) {
        this.maxDosage = maxDosage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.min_dosage
     *
     * @return the value of material.min_dosage
     *
     * @mbggenerated Wed May 09 16:40:58 CST 2018
     */
    public Double getMinDosage() {
        return minDosage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.min_dosage
     *
     * @param minDosage the value for material.min_dosage
     *
     * @mbggenerated Wed May 09 16:40:58 CST 2018
     */
    public void setMinDosage(Double minDosage) {
        this.minDosage = minDosage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.unit
     *
     * @return the value of material.unit
     *
     * @mbggenerated Wed May 09 16:40:58 CST 2018
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.unit
     *
     * @param unit the value for material.unit
     *
     * @mbggenerated Wed May 09 16:40:58 CST 2018
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.xw
     *
     * @return the value of material.xw
     *
     * @mbggenerated Wed May 09 16:40:58 CST 2018
     */
    public String getXw() {
        return xw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.xw
     *
     * @param xw the value for material.xw
     *
     * @mbggenerated Wed May 09 16:40:58 CST 2018
     */
    public void setXw(String xw) {
        this.xw = xw == null ? null : xw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.gj
     *
     * @return the value of material.gj
     *
     * @mbggenerated Wed May 09 16:40:58 CST 2018
     */
    public String getGj() {
        return gj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.gj
     *
     * @param gj the value for material.gj
     *
     * @mbggenerated Wed May 09 16:40:58 CST 2018
     */
    public void setGj(String gj) {
        this.gj = gj == null ? null : gj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.gx
     *
     * @return the value of material.gx
     *
     * @mbggenerated Wed May 09 16:40:58 CST 2018
     */
    public String getGx() {
        return gx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.gx
     *
     * @param gx the value for material.gx
     *
     * @mbggenerated Wed May 09 16:40:58 CST 2018
     */
    public void setGx(String gx) {
        this.gx = gx == null ? null : gx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.zz
     *
     * @return the value of material.zz
     *
     * @mbggenerated Wed May 09 16:40:58 CST 2018
     */
    public String getZz() {
        return zz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.zz
     *
     * @param zz the value for material.zz
     *
     * @mbggenerated Wed May 09 16:40:58 CST 2018
     */
    public void setZz(String zz) {
        this.zz = zz == null ? null : zz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.yf
     *
     * @return the value of material.yf
     *
     * @mbggenerated Wed May 09 16:40:58 CST 2018
     */
    public String getYf() {
        return yf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.yf
     *
     * @param yf the value for material.yf
     *
     * @mbggenerated Wed May 09 16:40:58 CST 2018
     */
    public void setYf(String yf) {
        this.yf = yf == null ? null : yf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.forbidden
     *
     * @return the value of material.forbidden
     *
     * @mbggenerated Wed May 09 16:40:58 CST 2018
     */
    public String getForbidden() {
        return forbidden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.forbidden
     *
     * @param forbidden the value for material.forbidden
     *
     * @mbggenerated Wed May 09 16:40:58 CST 2018
     */
    public void setForbidden(String forbidden) {
        this.forbidden = forbidden == null ? null : forbidden.trim();
    }

    public String getFscode() {
        return fscode;
    }

    public void setFscode(String fscode) {
        this.fscode = fscode;
    }
}