package com.cdutcm.tcms.biz.service;

import java.util.List;

import com.cdutcm.core.message.SysMsg;
import com.cdutcm.tcms.biz.model.Emr;
import com.cdutcm.tcms.biz.model.Material;
import com.cdutcm.tcms.biz.model.RecipelItem;

public interface MaterialService {
	
	//查出所有药品
	List<Material> selectAll();
	
	SysMsg updatePinyin(List<Material> record);
	
	 Material selectByName(String  name);
	 /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material
     *
     * @mbggenerated Wed May 09 16:40:58 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material
     *
     * @mbggenerated Wed May 09 16:40:58 CST 2018
     */
    int insert(Material record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material
     *
     * @mbggenerated Wed May 09 16:40:58 CST 2018
     */
    int insertSelective(Material record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material
     *
     * @mbggenerated Wed May 09 16:40:58 CST 2018
     */
    Material selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material
     *
     * @mbggenerated Wed May 09 16:40:58 CST 2018
     */
    int updateByPrimaryKeySelective(Material record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material
     *
     * @mbggenerated Wed May 09 16:40:58 CST 2018
     */
    int updateByPrimaryKey(Material record);
    
    List<Material> findByDurgList(List<RecipelItem> recipelItem);

	String drugRule(Emr emr);
	
	List<Material> findbynameorpinyin(String material);
	/**
	 * 分页查询药瓶自动补全
	 */
	List<Material> listPagefindmaterial(Material material);

}
