package com.cdutcm.tcms.biz.service;


import java.util.List;

import com.cdutcm.tcms.biz.model.UserInfo;
import com.cdutcm.tcms.sys.entity.User;



public interface UserInfoService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Wed May 09 11:13:55 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Wed May 09 11:13:55 CST 2018
     */
    int insert(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Wed May 09 11:13:55 CST 2018
     */
    int insertSelective(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Wed May 09 11:13:55 CST 2018
     */
    User selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Wed May 09 11:13:55 CST 2018
     */
    int updateByPrimaryKeySelective(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Wed May 09 11:13:55 CST 2018
     */
    int updateByPrimaryKey(UserInfo record);
    
    int addUserInfoList(List<UserInfo> userInfos);
    
    int deleteAll();
}
