package com.cdutcm.tcms.junqu.mapper;

import java.util.List;

import com.cdutcm.tcms.biz.model.Emr;
import com.cdutcm.tcms.junqu.model.EmrView;

public interface EmrViewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_ZYY_OUTP_MR
     *
     * @mbggenerated Tue May 08 14:17:10 CST 2018
     */
    int deleteByPrimaryKey(Integer visitNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_ZYY_OUTP_MR
     *
     * @mbggenerated Tue May 08 14:17:10 CST 2018
     */
    int insert(EmrView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_ZYY_OUTP_MR
     *
     * @mbggenerated Tue May 08 14:17:10 CST 2018
     */
    int insertSelective(EmrView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_ZYY_OUTP_MR
     *
     * @mbggenerated Tue May 08 14:17:10 CST 2018
     */
    EmrView selectByPrimaryKey(Integer visitNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_ZYY_OUTP_MR
     *
     * @mbggenerated Tue May 08 14:17:10 CST 2018
     */
    int updateByPrimaryKeySelective(EmrView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_ZYY_OUTP_MR
     *
     * @mbggenerated Tue May 08 14:17:10 CST 2018
     */
    int updateByPrimaryKey(EmrView record);
    
    List<Emr> findEmrBy(Emr e);
    
    List<EmrView> findEmrBYDateAndNo(String Date, String visitNo);
}