package com.cdutcm.tcms.junqu.mapper;

import java.util.List;

import com.cdutcm.tcms.biz.model.Recipel;
import com.cdutcm.tcms.junqu.model.RecipelView;

public interface RecipelViewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_ZYY_OUTP_PREC
     *
     * @mbggenerated Tue May 08 11:55:35 CST 2018
     */
    int insert(RecipelView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_ZYY_OUTP_PREC
     *
     * @mbggenerated Tue May 08 11:55:35 CST 2018
     */
    int insertSelective(RecipelView record);
    
    List<RecipelView> findRecipelBYDateAndNo(String date,String visitNo);
}