package com.cdutcm.tcms.junqu.service;

import java.util.List;

import com.cdutcm.tcms.biz.model.Emr;
import com.cdutcm.tcms.biz.model.Recipel;
import com.cdutcm.tcms.junqu.model.EmrView;
import com.cdutcm.tcms.junqu.model.PatientView;
import com.cdutcm.tcms.junqu.model.RecipelView;

public interface EmrViewService {
	  /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_ZYY_OUTP_MR
     *
     * @mbggenerated Tue May 08 14:17:10 CST 2018
     */
   public int deleteByPrimaryKey(Integer visitNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_ZYY_OUTP_MR
     *
     * @mbggenerated Tue May 08 14:17:10 CST 2018
     */
   public  int insert(EmrView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_ZYY_OUTP_MR
     *
     * @mbggenerated Tue May 08 14:17:10 CST 2018
     */
   public int insertSelective(EmrView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_ZYY_OUTP_MR
     *
     * @mbggenerated Tue May 08 14:17:10 CST 2018
     */
   public EmrView selectByPrimaryKey(Integer visitNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_ZYY_OUTP_MR
     *
     * @mbggenerated Tue May 08 14:17:10 CST 2018
     */
   public int updateByPrimaryKeySelective(EmrView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_ZYY_OUTP_MR
     *
     * @mbggenerated Tue May 08 14:17:10 CST 2018
     */
   public int updateByPrimaryKey(EmrView record);
    
   public List<Emr> findEmrBy(Emr e);
   
   List<RecipelView> findRecipelBYDateAndNo(String date,String visitNo);
   
   List<PatientView> findPatientByDateAndNo (String date ,String visitNo);
   
   List<EmrView> findEmrBYDateAndNo(String Date, String visitNo);
}
