package com.cdutcm.tcms.junqu.model;

import java.util.Date;

public class DoctorView {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ZYY_DOCTOR.USER_ID
     *
     * @mbggenerated Tue May 08 14:14:13 CST 2018
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ZYY_DOCTOR.DB_USER
     *
     * @mbggenerated Tue May 08 14:14:13 CST 2018
     */
    private String dbUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ZYY_DOCTOR.USER_NAME
     *
     * @mbggenerated Tue May 08 14:14:13 CST 2018
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ZYY_DOCTOR.USER_DEPT
     *
     * @mbggenerated Tue May 08 14:14:13 CST 2018
     */
    private String userDept;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ZYY_DOCTOR.DEPT_NAME
     *
     * @mbggenerated Tue May 08 14:14:13 CST 2018
     */
    private String deptName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ZYY_DOCTOR.USER_PWD
     *
     * @mbggenerated Tue May 08 14:14:13 CST 2018
     */
    private String userPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ZYY_DOCTOR.ROLE_ID
     *
     * @mbggenerated Tue May 08 14:14:13 CST 2018
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ZYY_DOCTOR.CLASS_ID
     *
     * @mbggenerated Tue May 08 14:14:13 CST 2018
     */
    private Short classId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ZYY_DOCTOR.GRADE
     *
     * @mbggenerated Tue May 08 14:14:13 CST 2018
     */
    private Short grade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ZYY_DOCTOR.START_DATE
     *
     * @mbggenerated Tue May 08 14:14:13 CST 2018
     */
    private Date startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ZYY_DOCTOR.END_DATE
     *
     * @mbggenerated Tue May 08 14:14:13 CST 2018
     */
    private Date endDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ZYY_DOCTOR.USER_ID
     *
     * @return the value of V_ZYY_DOCTOR.USER_ID
     *
     * @mbggenerated Tue May 08 14:14:13 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ZYY_DOCTOR.USER_ID
     *
     * @param userId the value for V_ZYY_DOCTOR.USER_ID
     *
     * @mbggenerated Tue May 08 14:14:13 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ZYY_DOCTOR.DB_USER
     *
     * @return the value of V_ZYY_DOCTOR.DB_USER
     *
     * @mbggenerated Tue May 08 14:14:13 CST 2018
     */
    public String getDbUser() {
        return dbUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ZYY_DOCTOR.DB_USER
     *
     * @param dbUser the value for V_ZYY_DOCTOR.DB_USER
     *
     * @mbggenerated Tue May 08 14:14:13 CST 2018
     */
    public void setDbUser(String dbUser) {
        this.dbUser = dbUser == null ? null : dbUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ZYY_DOCTOR.USER_NAME
     *
     * @return the value of V_ZYY_DOCTOR.USER_NAME
     *
     * @mbggenerated Tue May 08 14:14:13 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ZYY_DOCTOR.USER_NAME
     *
     * @param userName the value for V_ZYY_DOCTOR.USER_NAME
     *
     * @mbggenerated Tue May 08 14:14:13 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ZYY_DOCTOR.USER_DEPT
     *
     * @return the value of V_ZYY_DOCTOR.USER_DEPT
     *
     * @mbggenerated Tue May 08 14:14:13 CST 2018
     */
    public String getUserDept() {
        return userDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ZYY_DOCTOR.USER_DEPT
     *
     * @param userDept the value for V_ZYY_DOCTOR.USER_DEPT
     *
     * @mbggenerated Tue May 08 14:14:13 CST 2018
     */
    public void setUserDept(String userDept) {
        this.userDept = userDept == null ? null : userDept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ZYY_DOCTOR.DEPT_NAME
     *
     * @return the value of V_ZYY_DOCTOR.DEPT_NAME
     *
     * @mbggenerated Tue May 08 14:14:13 CST 2018
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ZYY_DOCTOR.DEPT_NAME
     *
     * @param deptName the value for V_ZYY_DOCTOR.DEPT_NAME
     *
     * @mbggenerated Tue May 08 14:14:13 CST 2018
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName == null ? null : deptName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ZYY_DOCTOR.USER_PWD
     *
     * @return the value of V_ZYY_DOCTOR.USER_PWD
     *
     * @mbggenerated Tue May 08 14:14:13 CST 2018
     */
    public String getUserPwd() {
        return userPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ZYY_DOCTOR.USER_PWD
     *
     * @param userPwd the value for V_ZYY_DOCTOR.USER_PWD
     *
     * @mbggenerated Tue May 08 14:14:13 CST 2018
     */
    public void setUserPwd(String userPwd) {
        this.userPwd = userPwd == null ? null : userPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ZYY_DOCTOR.ROLE_ID
     *
     * @return the value of V_ZYY_DOCTOR.ROLE_ID
     *
     * @mbggenerated Tue May 08 14:14:13 CST 2018
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ZYY_DOCTOR.ROLE_ID
     *
     * @param roleId the value for V_ZYY_DOCTOR.ROLE_ID
     *
     * @mbggenerated Tue May 08 14:14:13 CST 2018
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ZYY_DOCTOR.CLASS_ID
     *
     * @return the value of V_ZYY_DOCTOR.CLASS_ID
     *
     * @mbggenerated Tue May 08 14:14:13 CST 2018
     */
    public Short getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ZYY_DOCTOR.CLASS_ID
     *
     * @param classId the value for V_ZYY_DOCTOR.CLASS_ID
     *
     * @mbggenerated Tue May 08 14:14:13 CST 2018
     */
    public void setClassId(Short classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ZYY_DOCTOR.GRADE
     *
     * @return the value of V_ZYY_DOCTOR.GRADE
     *
     * @mbggenerated Tue May 08 14:14:13 CST 2018
     */
    public Short getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ZYY_DOCTOR.GRADE
     *
     * @param grade the value for V_ZYY_DOCTOR.GRADE
     *
     * @mbggenerated Tue May 08 14:14:13 CST 2018
     */
    public void setGrade(Short grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ZYY_DOCTOR.START_DATE
     *
     * @return the value of V_ZYY_DOCTOR.START_DATE
     *
     * @mbggenerated Tue May 08 14:14:13 CST 2018
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ZYY_DOCTOR.START_DATE
     *
     * @param startDate the value for V_ZYY_DOCTOR.START_DATE
     *
     * @mbggenerated Tue May 08 14:14:13 CST 2018
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ZYY_DOCTOR.END_DATE
     *
     * @return the value of V_ZYY_DOCTOR.END_DATE
     *
     * @mbggenerated Tue May 08 14:14:13 CST 2018
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ZYY_DOCTOR.END_DATE
     *
     * @param endDate the value for V_ZYY_DOCTOR.END_DATE
     *
     * @mbggenerated Tue May 08 14:14:13 CST 2018
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
}