package com.cdutcm.tcms.junqu.model;

import java.io.UnsupportedEncodingException;
import java.util.Date;

public class EmrView {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ZYY_OUTP_MR.VISIT_NO
     *
     * @mbggenerated Tue May 08 14:17:10 CST 2018
     */
    private Integer visitNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ZYY_OUTP_MR.VISIT_DATE
     *
     * @mbggenerated Tue May 08 14:17:10 CST 2018
     */
    private Date visitDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ZYY_OUTP_MR.PATIENT_ID
     *
     * @mbggenerated Tue May 08 14:17:10 CST 2018
     */
    private String patientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ZYY_OUTP_MR.DIAG_DESC
     *
     * @mbggenerated Tue May 08 14:17:10 CST 2018
     */
    private String diagDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ZYY_OUTP_MR.ILLNESS_DESC
     *
     * @mbggenerated Tue May 08 14:17:10 CST 2018
     */
    private String illnessDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ZYY_OUTP_MR.ANAMNESIS
     *
     * @mbggenerated Tue May 08 14:17:10 CST 2018
     */
    private String anamnesis;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ZYY_OUTP_MR.FAMILY_ILL
     *
     * @mbggenerated Tue May 08 14:17:10 CST 2018
     */
    private String familyIll;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ZYY_OUTP_MR.MARRITAL
     *
     * @mbggenerated Tue May 08 14:17:10 CST 2018
     */
    private String marrital;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ZYY_OUTP_MR.INDIVIDUAL
     *
     * @mbggenerated Tue May 08 14:17:10 CST 2018
     */
    private String individual;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ZYY_OUTP_MR.MENSES
     *
     * @mbggenerated Tue May 08 14:17:10 CST 2018
     */
    private String menses;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ZYY_OUTP_MR.MED_HISTORY
     *
     * @mbggenerated Tue May 08 14:17:10 CST 2018
     */
    private String medHistory;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ZYY_OUTP_MR.VISIT_NO
     *
     * @return the value of V_ZYY_OUTP_MR.VISIT_NO
     *
     * @mbggenerated Tue May 08 14:17:10 CST 2018
     */
    public Integer getVisitNo() {
        return visitNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ZYY_OUTP_MR.VISIT_NO
     *
     * @param visitNo the value for V_ZYY_OUTP_MR.VISIT_NO
     *
     * @mbggenerated Tue May 08 14:17:10 CST 2018
     */
    public void setVisitNo(Integer visitNo) {
        this.visitNo = visitNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ZYY_OUTP_MR.VISIT_DATE
     *
     * @return the value of V_ZYY_OUTP_MR.VISIT_DATE
     *
     * @mbggenerated Tue May 08 14:17:10 CST 2018
     */
    public Date getVisitDate() {
        return visitDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ZYY_OUTP_MR.VISIT_DATE
     *
     * @param visitDate the value for V_ZYY_OUTP_MR.VISIT_DATE
     *
     * @mbggenerated Tue May 08 14:17:10 CST 2018
     */
    public void setVisitDate(Date visitDate) {
        this.visitDate = visitDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ZYY_OUTP_MR.PATIENT_ID
     *
     * @return the value of V_ZYY_OUTP_MR.PATIENT_ID
     *
     * @mbggenerated Tue May 08 14:17:10 CST 2018
     */
    public String getPatientId() {
        return patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ZYY_OUTP_MR.PATIENT_ID
     *
     * @param patientId the value for V_ZYY_OUTP_MR.PATIENT_ID
     *
     * @mbggenerated Tue May 08 14:17:10 CST 2018
     */
    public void setPatientId(String patientId) {
        this.patientId = patientId == null ? null : patientId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ZYY_OUTP_MR.DIAG_DESC
     *
     * @return the value of V_ZYY_OUTP_MR.DIAG_DESC
     *
     * @mbggenerated Tue May 08 14:17:10 CST 2018
     */
    public String getDiagDesc() {
        return diagDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ZYY_OUTP_MR.DIAG_DESC
     *
     * @param diagDesc the value for V_ZYY_OUTP_MR.DIAG_DESC
     *
     * @mbggenerated Tue May 08 14:17:10 CST 2018
     */
    public void setDiagDesc(String diagDesc) {
        try {
            this.diagDesc = diagDesc == null ? null : new String(diagDesc.toString().getBytes("ISO-8859-1"), "GBK");
        } catch (UnsupportedEncodingException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ZYY_OUTP_MR.ILLNESS_DESC
     *
     * @return the value of V_ZYY_OUTP_MR.ILLNESS_DESC
     *
     * @mbggenerated Tue May 08 14:17:10 CST 2018
     */
    public String getIllnessDesc() {
        return illnessDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ZYY_OUTP_MR.ILLNESS_DESC
     *
     * @param illnessDesc the value for V_ZYY_OUTP_MR.ILLNESS_DESC
     *
     * @mbggenerated Tue May 08 14:17:10 CST 2018
     */
    public void setIllnessDesc(String illnessDesc) {
        try {
            this.illnessDesc = illnessDesc == null ? null : new String(illnessDesc.toString().getBytes("ISO-8859-1"), "GBK");
        } catch (UnsupportedEncodingException e) {
            e.printStackTrace();
        }
        ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ZYY_OUTP_MR.ANAMNESIS
     *
     * @return the value of V_ZYY_OUTP_MR.ANAMNESIS
     *
     * @mbggenerated Tue May 08 14:17:10 CST 2018
     */
    public String getAnamnesis() {
        return anamnesis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ZYY_OUTP_MR.ANAMNESIS
     *
     * @param anamnesis the value for V_ZYY_OUTP_MR.ANAMNESIS
     *
     * @mbggenerated Tue May 08 14:17:10 CST 2018
     */
    public void setAnamnesis(String anamnesis) {
        try {
            this.anamnesis = anamnesis == null ? null : new String(anamnesis.toString().getBytes("ISO-8859-1"), "GBK");
        } catch (UnsupportedEncodingException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ZYY_OUTP_MR.FAMILY_ILL
     *
     * @return the value of V_ZYY_OUTP_MR.FAMILY_ILL
     *
     * @mbggenerated Tue May 08 14:17:10 CST 2018
     */
    public String getFamilyIll() {
        return familyIll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ZYY_OUTP_MR.FAMILY_ILL
     *
     * @param familyIll the value for V_ZYY_OUTP_MR.FAMILY_ILL
     *
     * @mbggenerated Tue May 08 14:17:10 CST 2018
     */
    public void setFamilyIll(String familyIll) {
        try {
            this.familyIll = familyIll == null ? null : new String(familyIll.toString().getBytes("ISO-8859-1"), "GBK");
        } catch (UnsupportedEncodingException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ZYY_OUTP_MR.MARRITAL
     *
     * @return the value of V_ZYY_OUTP_MR.MARRITAL
     *
     * @mbggenerated Tue May 08 14:17:10 CST 2018
     */
    public String getMarrital() {
        return marrital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ZYY_OUTP_MR.MARRITAL
     *
     * @param marrital the value for V_ZYY_OUTP_MR.MARRITAL
     *
     * @mbggenerated Tue May 08 14:17:10 CST 2018
     */
    public void setMarrital(String marrital) {
        try {
            this.marrital = marrital == null ? null : new String(marrital.toString().getBytes("ISO-8859-1"), "GBK");
        } catch (UnsupportedEncodingException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ZYY_OUTP_MR.INDIVIDUAL
     *
     * @return the value of V_ZYY_OUTP_MR.INDIVIDUAL
     *
     * @mbggenerated Tue May 08 14:17:10 CST 2018
     */
    public String getIndividual() {
        return individual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ZYY_OUTP_MR.INDIVIDUAL
     *
     * @param individual the value for V_ZYY_OUTP_MR.INDIVIDUAL
     *
     * @mbggenerated Tue May 08 14:17:10 CST 2018
     */
    public void setIndividual(String individual) {
        try {
            this.individual = individual == null ? null : new String(individual.toString().getBytes("ISO-8859-1"), "GBK");
        } catch (UnsupportedEncodingException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ZYY_OUTP_MR.MENSES
     *
     * @return the value of V_ZYY_OUTP_MR.MENSES
     *
     * @mbggenerated Tue May 08 14:17:10 CST 2018
     */
    public String getMenses() {
        return menses;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ZYY_OUTP_MR.MENSES
     *
     * @param menses the value for V_ZYY_OUTP_MR.MENSES
     *
     * @mbggenerated Tue May 08 14:17:10 CST 2018
     */
    public void setMenses(String menses) {
        try {
            this.menses = menses == null ? null :  new String(menses.toString().getBytes("ISO-8859-1"), "GBK");
        } catch (UnsupportedEncodingException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ZYY_OUTP_MR.MED_HISTORY
     *
     * @return the value of V_ZYY_OUTP_MR.MED_HISTORY
     *
     * @mbggenerated Tue May 08 14:17:10 CST 2018
     */
    public String getMedHistory() {
        return medHistory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ZYY_OUTP_MR.MED_HISTORY
     *
     * @param medHistory the value for V_ZYY_OUTP_MR.MED_HISTORY
     *
     * @mbggenerated Tue May 08 14:17:10 CST 2018
     */
    public void setMedHistory(String medHistory) {
        try {
            this.medHistory = medHistory == null ? null :  new String(medHistory.toString().getBytes("ISO-8859-1"), "GBK");
        } catch (UnsupportedEncodingException e) {
            e.printStackTrace();
        }
    }
}