package com.cdutcm.tcms.junqu.model;

import java.io.UnsupportedEncodingException;
import java.util.Date;

public class PatientView {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ZYY_CLINIC_MASTER.VISIT_NO
     *
     * @mbggenerated Tue May 08 14:16:07 CST 2018
     */
    private Short visitNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ZYY_CLINIC_MASTER.PATIENT_ID
     *
     * @mbggenerated Tue May 08 14:16:07 CST 2018
     */
    private String patientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ZYY_CLINIC_MASTER.NAME
     *
     * @mbggenerated Tue May 08 14:16:07 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ZYY_CLINIC_MASTER.NAME_PHONETIC
     *
     * @mbggenerated Tue May 08 14:16:07 CST 2018
     */
    private String namePhonetic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ZYY_CLINIC_MASTER.SEX
     *
     * @mbggenerated Tue May 08 14:16:07 CST 2018
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ZYY_CLINIC_MASTER.DATE_OF_BIRTH
     *
     * @mbggenerated Tue May 08 14:16:07 CST 2018
     */
    private Date dateOfBirth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ZYY_CLINIC_MASTER.MAILING_ADDRESS
     *
     * @mbggenerated Tue May 08 14:16:07 CST 2018
     */
    private String mailingAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ZYY_CLINIC_MASTER.PHONE_NUMBER_HOME
     *
     * @mbggenerated Tue May 08 14:16:07 CST 2018
     */
    private String phoneNumberHome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ZYY_CLINIC_MASTER.VISIT_DATE
     *
     * @mbggenerated Tue May 08 14:16:07 CST 2018
     */
    private Date visitDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ZYY_CLINIC_MASTER.SERIAL_NO
     *
     * @mbggenerated Tue May 08 14:16:07 CST 2018
     */
    private Short serialNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ZYY_CLINIC_MASTER.CLINIC_LABEL
     *
     * @mbggenerated Tue May 08 14:16:07 CST 2018
     */
    private String clinicLabel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ZYY_CLINIC_MASTER.FIRST_VISIT_INDICATOR
     *
     * @mbggenerated Tue May 08 14:16:07 CST 2018
     */
    private Short firstVisitIndicator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ZYY_CLINIC_MASTER.VISIT_DEPT
     *
     * @mbggenerated Tue May 08 14:16:07 CST 2018
     */
    private String visitDept;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ZYY_CLINIC_MASTER.DEPT_NAME
     *
     * @mbggenerated Tue May 08 14:16:07 CST 2018
     */
    private String deptName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ZYY_CLINIC_MASTER.DOCTOR
     *
     * @mbggenerated Tue May 08 14:16:07 CST 2018
     */
    private String doctor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ZYY_CLINIC_MASTER.REGISTERING_DAT
     *
     * @mbggenerated Tue May 08 14:16:07 CST 2018
     */
    private Date registeringDat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ZYY_CLINIC_MASTER.VISIT_NO
     *
     * @return the value of V_ZYY_CLINIC_MASTER.VISIT_NO
     *
     * @mbggenerated Tue May 08 14:16:07 CST 2018
     */
    public Short getVisitNo() {
        return visitNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ZYY_CLINIC_MASTER.VISIT_NO
     *
     * @param visitNo the value for V_ZYY_CLINIC_MASTER.VISIT_NO
     *
     * @mbggenerated Tue May 08 14:16:07 CST 2018
     */
    public void setVisitNo(Short visitNo) {
        this.visitNo = visitNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ZYY_CLINIC_MASTER.PATIENT_ID
     *
     * @return the value of V_ZYY_CLINIC_MASTER.PATIENT_ID
     *
     * @mbggenerated Tue May 08 14:16:07 CST 2018
     */
    public String getPatientId() {
        return patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ZYY_CLINIC_MASTER.PATIENT_ID
     *
     * @param patientId the value for V_ZYY_CLINIC_MASTER.PATIENT_ID
     *
     * @mbggenerated Tue May 08 14:16:07 CST 2018
     */
    public void setPatientId(String patientId) {
        this.patientId = patientId == null ? null : patientId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ZYY_CLINIC_MASTER.NAME
     *
     * @return the value of V_ZYY_CLINIC_MASTER.NAME
     *
     * @mbggenerated Tue May 08 14:16:07 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ZYY_CLINIC_MASTER.NAME
     *
     * @param name the value for V_ZYY_CLINIC_MASTER.NAME
     *
     * @mbggenerated Tue May 08 14:16:07 CST 2018
     */
    public void setName(String name) {
        try {
            this.name = name == null ? null : new String(name.toString().getBytes("ISO-8859-1"), "GBK");
        }catch (UnsupportedEncodingException e){
            e.printStackTrace();
        }

    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ZYY_CLINIC_MASTER.NAME_PHONETIC
     *
     * @return the value of V_ZYY_CLINIC_MASTER.NAME_PHONETIC
     *
     * @mbggenerated Tue May 08 14:16:07 CST 2018
     */
    public String getNamePhonetic() {
        return namePhonetic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ZYY_CLINIC_MASTER.NAME_PHONETIC
     *
     * @param namePhonetic the value for V_ZYY_CLINIC_MASTER.NAME_PHONETIC
     *
     * @mbggenerated Tue May 08 14:16:07 CST 2018
     */
    public void setNamePhonetic(String namePhonetic) {
        this.namePhonetic = namePhonetic == null ? null : namePhonetic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ZYY_CLINIC_MASTER.SEX
     *
     * @return the value of V_ZYY_CLINIC_MASTER.SEX
     *
     * @mbggenerated Tue May 08 14:16:07 CST 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ZYY_CLINIC_MASTER.SEX
     *
     * @param sex the value for V_ZYY_CLINIC_MASTER.SEX
     *
     * @mbggenerated Tue May 08 14:16:07 CST 2018
     */
    public void setSex(String sex) {
        try {
            this.sex = sex == null ? null :new String(sex.getBytes("ISO-8859-1"), "GBK");
        } catch (UnsupportedEncodingException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ZYY_CLINIC_MASTER.DATE_OF_BIRTH
     *
     * @return the value of V_ZYY_CLINIC_MASTER.DATE_OF_BIRTH
     *
     * @mbggenerated Tue May 08 14:16:07 CST 2018
     */
    public Date getDateOfBirth() {
        return dateOfBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ZYY_CLINIC_MASTER.DATE_OF_BIRTH
     *
     * @param dateOfBirth the value for V_ZYY_CLINIC_MASTER.DATE_OF_BIRTH
     *
     * @mbggenerated Tue May 08 14:16:07 CST 2018
     */
    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ZYY_CLINIC_MASTER.MAILING_ADDRESS
     *
     * @return the value of V_ZYY_CLINIC_MASTER.MAILING_ADDRESS
     *
     * @mbggenerated Tue May 08 14:16:07 CST 2018
     */
    public String getMailingAddress() {
        return mailingAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ZYY_CLINIC_MASTER.MAILING_ADDRESS
     *
     * @param mailingAddress the value for V_ZYY_CLINIC_MASTER.MAILING_ADDRESS
     *
     * @mbggenerated Tue May 08 14:16:07 CST 2018
     */
    public void setMailingAddress(String mailingAddress) {
        try {
            this.mailingAddress = mailingAddress == null ? null : new String(mailingAddress.getBytes("ISO-8859-1"), "GBK");
        } catch (UnsupportedEncodingException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ZYY_CLINIC_MASTER.PHONE_NUMBER_HOME
     *
     * @return the value of V_ZYY_CLINIC_MASTER.PHONE_NUMBER_HOME
     *
     * @mbggenerated Tue May 08 14:16:07 CST 2018
     */
    public String getPhoneNumberHome() {
        return phoneNumberHome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ZYY_CLINIC_MASTER.PHONE_NUMBER_HOME
     *
     * @param phoneNumberHome the value for V_ZYY_CLINIC_MASTER.PHONE_NUMBER_HOME
     *
     * @mbggenerated Tue May 08 14:16:07 CST 2018
     */
    public void setPhoneNumberHome(String phoneNumberHome) {
        this.phoneNumberHome = phoneNumberHome == null ? null : phoneNumberHome.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ZYY_CLINIC_MASTER.VISIT_DATE
     *
     * @return the value of V_ZYY_CLINIC_MASTER.VISIT_DATE
     *
     * @mbggenerated Tue May 08 14:16:07 CST 2018
     */
    public Date getVisitDate() {
        return visitDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ZYY_CLINIC_MASTER.VISIT_DATE
     *
     * @param visitDate the value for V_ZYY_CLINIC_MASTER.VISIT_DATE
     *
     * @mbggenerated Tue May 08 14:16:07 CST 2018
     */
    public void setVisitDate(Date visitDate) {
        this.visitDate = visitDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ZYY_CLINIC_MASTER.SERIAL_NO
     *
     * @return the value of V_ZYY_CLINIC_MASTER.SERIAL_NO
     *
     * @mbggenerated Tue May 08 14:16:07 CST 2018
     */
    public Short getSerialNo() {
        return serialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ZYY_CLINIC_MASTER.SERIAL_NO
     *
     * @param serialNo the value for V_ZYY_CLINIC_MASTER.SERIAL_NO
     *
     * @mbggenerated Tue May 08 14:16:07 CST 2018
     */
    public void setSerialNo(Short serialNo) {
        this.serialNo = serialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ZYY_CLINIC_MASTER.CLINIC_LABEL
     *
     * @return the value of V_ZYY_CLINIC_MASTER.CLINIC_LABEL
     *
     * @mbggenerated Tue May 08 14:16:07 CST 2018
     */
    public String getClinicLabel() {
        return clinicLabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ZYY_CLINIC_MASTER.CLINIC_LABEL
     *
     * @param clinicLabel the value for V_ZYY_CLINIC_MASTER.CLINIC_LABEL
     *
     * @mbggenerated Tue May 08 14:16:07 CST 2018
     */
    public void setClinicLabel(String clinicLabel) {
        try {
            this.clinicLabel = clinicLabel == null ? null : new String(clinicLabel.toString().getBytes("ISO-8859-1"), "GBK");
        } catch (UnsupportedEncodingException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ZYY_CLINIC_MASTER.FIRST_VISIT_INDICATOR
     *
     * @return the value of V_ZYY_CLINIC_MASTER.FIRST_VISIT_INDICATOR
     *
     * @mbggenerated Tue May 08 14:16:07 CST 2018
     */
    public Short getFirstVisitIndicator() {
        return firstVisitIndicator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ZYY_CLINIC_MASTER.FIRST_VISIT_INDICATOR
     *
     * @param firstVisitIndicator the value for V_ZYY_CLINIC_MASTER.FIRST_VISIT_INDICATOR
     *
     * @mbggenerated Tue May 08 14:16:07 CST 2018
     */
    public void setFirstVisitIndicator(Short firstVisitIndicator) {
        this.firstVisitIndicator = firstVisitIndicator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ZYY_CLINIC_MASTER.VISIT_DEPT
     *
     * @return the value of V_ZYY_CLINIC_MASTER.VISIT_DEPT
     *
     * @mbggenerated Tue May 08 14:16:07 CST 2018
     */
    public String getVisitDept() {
        return visitDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ZYY_CLINIC_MASTER.VISIT_DEPT
     *
     * @param visitDept the value for V_ZYY_CLINIC_MASTER.VISIT_DEPT
     *
     * @mbggenerated Tue May 08 14:16:07 CST 2018
     */
    public void setVisitDept(String visitDept) {
        this.visitDept = visitDept == null ? null : visitDept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ZYY_CLINIC_MASTER.DEPT_NAME
     *
     * @return the value of V_ZYY_CLINIC_MASTER.DEPT_NAME
     *
     * @mbggenerated Tue May 08 14:16:07 CST 2018
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ZYY_CLINIC_MASTER.DEPT_NAME
     *
     * @param deptName the value for V_ZYY_CLINIC_MASTER.DEPT_NAME
     *
     * @mbggenerated Tue May 08 14:16:07 CST 2018
     */
    public void setDeptName(String deptName) {
        try {
            this.deptName = deptName == null ? null : new String(deptName.toString().getBytes("ISO-8859-1"), "GBK");
        } catch (UnsupportedEncodingException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ZYY_CLINIC_MASTER.DOCTOR
     *
     * @return the value of V_ZYY_CLINIC_MASTER.DOCTOR
     *
     * @mbggenerated Tue May 08 14:16:07 CST 2018
     */
    public String getDoctor() {
        return doctor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ZYY_CLINIC_MASTER.DOCTOR
     *
     * @param doctor the value for V_ZYY_CLINIC_MASTER.DOCTOR
     *
     * @mbggenerated Tue May 08 14:16:07 CST 2018
     */
    public void setDoctor(String doctor) {
        try {
            this.doctor = doctor == null ? null : new String(doctor.toString().getBytes("ISO-8859-1"), "GBK");
        } catch (UnsupportedEncodingException e) {
            e.printStackTrace();
        }
    }
        /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ZYY_CLINIC_MASTER.REGISTERING_DAT
     *
     * @return the value of V_ZYY_CLINIC_MASTER.REGISTERING_DAT
     *
     * @mbggenerated Tue May 08 14:16:07 CST 2018
     */
    public Date getRegisteringDat() {
        return registeringDat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ZYY_CLINIC_MASTER.REGISTERING_DAT
     *
     * @param registeringDat the value for V_ZYY_CLINIC_MASTER.REGISTERING_DAT
     *
     * @mbggenerated Tue May 08 14:16:07 CST 2018
     */
    public void setRegisteringDat(Date registeringDat) {
        this.registeringDat = registeringDat;
    }
}