package com.cdutcm.tcms.junqu.model;

import java.io.UnsupportedEncodingException;
import java.math.BigDecimal;
import java.util.Date;

public class RecipelView {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ZYY_OUTP_PREC.VISIT_DATE
     *
     * @mbggenerated Tue May 08 11:55:35 CST 2018
     */
    private Date visitDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ZYY_OUTP_PREC.VISIT_NO
     *
     * @mbggenerated Tue May 08 11:55:35 CST 2018
     */
    private String visitNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ZYY_OUTP_PREC.ITEM_NO
     *
     * @mbggenerated Tue May 08 11:55:35 CST 2018
     */
    private Short itemNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ZYY_OUTP_PREC.ITEM_CLASS
     *
     * @mbggenerated Tue May 08 11:55:35 CST 2018
     */
    private String itemClass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ZYY_OUTP_PREC.DRUG_CODE
     *
     * @mbggenerated Tue May 08 11:55:35 CST 2018
     */
    private String drugCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ZYY_OUTP_PREC.DRUG_NAME
     *
     * @mbggenerated Tue May 08 11:55:35 CST 2018
     */
    private String drugName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ZYY_OUTP_PREC.AMOUNT
     *
     * @mbggenerated Tue May 08 11:55:35 CST 2018
     */
    private Integer amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ZYY_OUTP_PREC.UNITS
     *
     * @mbggenerated Tue May 08 11:55:35 CST 2018
     */
    private String units;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ZYY_OUTP_PREC.REPETITION
     *
     * @mbggenerated Tue May 08 11:55:35 CST 2018
     */
    private Short repetition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ZYY_OUTP_PREC.DOSAGE
     *
     * @mbggenerated Tue May 08 11:55:35 CST 2018
     */
    private BigDecimal dosage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ZYY_OUTP_PREC.DOSAGE_UNITS
     *
     * @mbggenerated Tue May 08 11:55:35 CST 2018
     */
    private String dosageUnits;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ZYY_OUTP_PREC.ADMINISTRATION
     *
     * @mbggenerated Tue May 08 11:55:35 CST 2018
     */
    private String administration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ZYY_OUTP_PREC.FREQUENCY
     *
     * @mbggenerated Tue May 08 11:55:35 CST 2018
     */
    private String frequency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column V_ZYY_OUTP_PREC.DISPENSARY
     *
     * @mbggenerated Tue May 08 11:55:35 CST 2018
     */
    private String dispensary;


    private String serialNo;




    public String getSerialNo() {
        return serialNo;
    }

    public void setSerialNo(String serialNo) {
        this.serialNo = serialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ZYY_OUTP_PREC.VISIT_DATE
     *
     * @return the value of V_ZYY_OUTP_PREC.VISIT_DATE
     *
     * @mbggenerated Tue May 08 11:55:35 CST 2018
     */
    public Date getVisitDate() {
        return visitDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ZYY_OUTP_PREC.VISIT_DATE
     *
     * @param visitDate the value for V_ZYY_OUTP_PREC.VISIT_DATE
     *
     * @mbggenerated Tue May 08 11:55:35 CST 2018
     */
    public void setVisitDate(Date visitDate) {
        this.visitDate = visitDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ZYY_OUTP_PREC.VISIT_NO
     *
     * @return the value of V_ZYY_OUTP_PREC.VISIT_NO
     *
     * @mbggenerated Tue May 08 11:55:35 CST 2018
     */
    public String getVisitNo() {
        return visitNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ZYY_OUTP_PREC.VISIT_NO
     *
     * @param visitNo the value for V_ZYY_OUTP_PREC.VISIT_NO
     *
     * @mbggenerated Tue May 08 11:55:35 CST 2018
     */
    public void setVisitNo(String visitNo) {
        this.visitNo = visitNo == null ? null : visitNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ZYY_OUTP_PREC.ITEM_NO
     *
     * @return the value of V_ZYY_OUTP_PREC.ITEM_NO
     *
     * @mbggenerated Tue May 08 11:55:35 CST 2018
     */
    public Short getItemNo() {
        return itemNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ZYY_OUTP_PREC.ITEM_NO
     *
     * @param itemNo the value for V_ZYY_OUTP_PREC.ITEM_NO
     *
     * @mbggenerated Tue May 08 11:55:35 CST 2018
     */
    public void setItemNo(Short itemNo) {
        this.itemNo = itemNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ZYY_OUTP_PREC.ITEM_CLASS
     *
     * @return the value of V_ZYY_OUTP_PREC.ITEM_CLASS
     *
     * @mbggenerated Tue May 08 11:55:35 CST 2018
     */
    public String getItemClass() {
        return itemClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ZYY_OUTP_PREC.ITEM_CLASS
     *
     * @param itemClass the value for V_ZYY_OUTP_PREC.ITEM_CLASS
     *
     * @mbggenerated Tue May 08 11:55:35 CST 2018
     */
    public void setItemClass(String itemClass) {
        this.itemClass = itemClass == null ? null : itemClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ZYY_OUTP_PREC.DRUG_CODE
     *
     * @return the value of V_ZYY_OUTP_PREC.DRUG_CODE
     *
     * @mbggenerated Tue May 08 11:55:35 CST 2018
     */
    public String getDrugCode() {
        return drugCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ZYY_OUTP_PREC.DRUG_CODE
     *
     * @param drugCode the value for V_ZYY_OUTP_PREC.DRUG_CODE
     *
     * @mbggenerated Tue May 08 11:55:35 CST 2018
     */
    public void setDrugCode(String drugCode) {
        this.drugCode = drugCode == null ? null : drugCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ZYY_OUTP_PREC.DRUG_NAME
     *
     * @return the value of V_ZYY_OUTP_PREC.DRUG_NAME
     *
     * @mbggenerated Tue May 08 11:55:35 CST 2018
     */
    public String getDrugName() {
        return drugName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ZYY_OUTP_PREC.DRUG_NAME
     *
     * @param drugName the value for V_ZYY_OUTP_PREC.DRUG_NAME
     *
     * @mbggenerated Tue May 08 11:55:35 CST 2018
     */
    public void setDrugName(String drugName) {
        try {
            this.drugName = drugName == null ? null :new String(drugName.toString().getBytes("ISO-8859-1"), "GBK");
        } catch (UnsupportedEncodingException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ZYY_OUTP_PREC.AMOUNT
     *
     * @return the value of V_ZYY_OUTP_PREC.AMOUNT
     *
     * @mbggenerated Tue May 08 11:55:35 CST 2018
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ZYY_OUTP_PREC.AMOUNT
     *
     * @param amount the value for V_ZYY_OUTP_PREC.AMOUNT
     *
     * @mbggenerated Tue May 08 11:55:35 CST 2018
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ZYY_OUTP_PREC.UNITS
     *
     * @return the value of V_ZYY_OUTP_PREC.UNITS
     *
     * @mbggenerated Tue May 08 11:55:35 CST 2018
     */
    public String getUnits() {
        return units;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ZYY_OUTP_PREC.UNITS
     *
     * @param units the value for V_ZYY_OUTP_PREC.UNITS
     *
     * @mbggenerated Tue May 08 11:55:35 CST 2018
     */
    public void setUnits(String units) {
        this.units = units == null ? null : units.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ZYY_OUTP_PREC.REPETITION
     *
     * @return the value of V_ZYY_OUTP_PREC.REPETITION
     *
     * @mbggenerated Tue May 08 11:55:35 CST 2018
     */
    public Short getRepetition() {
        return repetition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ZYY_OUTP_PREC.REPETITION
     *
     * @param repetition the value for V_ZYY_OUTP_PREC.REPETITION
     *
     * @mbggenerated Tue May 08 11:55:35 CST 2018
     */
    public void setRepetition(Short repetition) {
        this.repetition = repetition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ZYY_OUTP_PREC.DOSAGE
     *
     * @return the value of V_ZYY_OUTP_PREC.DOSAGE
     *
     * @mbggenerated Tue May 08 11:55:35 CST 2018
     */
    public BigDecimal getDosage() {
        return dosage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ZYY_OUTP_PREC.DOSAGE
     *
     * @param dosage the value for V_ZYY_OUTP_PREC.DOSAGE
     *
     * @mbggenerated Tue May 08 11:55:35 CST 2018
     */
    public void setDosage(BigDecimal dosage) {
        this.dosage = dosage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ZYY_OUTP_PREC.DOSAGE_UNITS
     *
     * @return the value of V_ZYY_OUTP_PREC.DOSAGE_UNITS
     *
     * @mbggenerated Tue May 08 11:55:35 CST 2018
     */
    public String getDosageUnits() {
        return dosageUnits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ZYY_OUTP_PREC.DOSAGE_UNITS
     *
     * @param dosageUnits the value for V_ZYY_OUTP_PREC.DOSAGE_UNITS
     *
     * @mbggenerated Tue May 08 11:55:35 CST 2018
     */
    public void setDosageUnits(String dosageUnits) {
        this.dosageUnits = dosageUnits == null ? null : dosageUnits.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ZYY_OUTP_PREC.ADMINISTRATION
     *
     * @return the value of V_ZYY_OUTP_PREC.ADMINISTRATION
     *
     * @mbggenerated Tue May 08 11:55:35 CST 2018
     */
    public String getAdministration() {
        return administration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ZYY_OUTP_PREC.ADMINISTRATION
     *
     * @param administration the value for V_ZYY_OUTP_PREC.ADMINISTRATION
     *
     * @mbggenerated Tue May 08 11:55:35 CST 2018
     */
    public void setAdministration(String administration) {
        try {
            this.administration = administration == null ? null : new String(administration.toString().getBytes("ISO-8859-1"), "GBK");
        } catch (UnsupportedEncodingException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ZYY_OUTP_PREC.FREQUENCY
     *
     * @return the value of V_ZYY_OUTP_PREC.FREQUENCY
     *
     * @mbggenerated Tue May 08 11:55:35 CST 2018
     */
    public String getFrequency() {
        return frequency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ZYY_OUTP_PREC.FREQUENCY
     *
     * @param frequency the value for V_ZYY_OUTP_PREC.FREQUENCY
     *
     * @mbggenerated Tue May 08 11:55:35 CST 2018
     */
    public void setFrequency(String frequency) {
        try {
            this.frequency = frequency == null ? null : new String(frequency.toString().getBytes("ISO-8859-1"), "GBK");
        } catch (UnsupportedEncodingException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_ZYY_OUTP_PREC.DISPENSARY
     *
     * @return the value of V_ZYY_OUTP_PREC.DISPENSARY
     *
     * @mbggenerated Tue May 08 11:55:35 CST 2018
     */
    public String getDispensary() {
        return dispensary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_ZYY_OUTP_PREC.DISPENSARY
     *
     * @param dispensary the value for V_ZYY_OUTP_PREC.DISPENSARY
     *
     * @mbggenerated Tue May 08 11:55:35 CST 2018
     */
    public void setDispensary(String dispensary) {
        this.dispensary = dispensary == null ? null : dispensary.trim();
    }
}